on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

name: Build My Apps

jobs:
  build_and_release:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Install dependencies
        run: flutter pub get

      - name: Replace string with GitHub secret
        run: sed -i 's/{GOOGLE_MAP_API_KEY}/${{ secrets.GOOGLE_MAP_API_KEY }}/g' android/app/src/main/AndroidManifest.xml

      - name: Build APK
        run: flutter build apk --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ steps.semvers.outputs.patch }}
          token: ${{ secrets.TOKEN }}


#  build_and_release_ios:
#    name: Build and Release new ipa
#    runs-on: macos-latest
#    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Replace string with GitHub secret IOS
#        run: sed -i 's/{GOOGLE_MAP_API_KEY}/${{ secrets.GOOGLE_MAP_API_KEY }}/g' ios/Runner/AppDelegate.swift
#
#      - uses: cedvdb/action-flutter-build-ios@v1
#        with:
#          build-cmd: flutter build ipa --release --flavor dev --export-options-plist=ios/GithubActionsExportOptions.plist
#          certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
#          certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
#          provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
#          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}
#
#      - name: Archive IPA
#        uses: actions/upload-artifact@v4
#        with:
#          name: release-ipa
#          path: 'build/ios/ipa/Trip memories.ipa'


  analyze_project:
    name: Analyze project source
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze
